export default {
    GET_SEARCH_VIOLATION_REQUEST:'GET_SEARCH_VIOLATION_REQUEST',
    GET_SEARCH_VIOLATION_FAILUTE:'GET_SEARCH_VIOLATION_FAILUTE',
    GET_SEARCH_VIOLATION_SUCCESS:'GET_SEARCH_VIOLATIO_SUCCESS'
}