// export const SHOW_INFOWINDOW_VIOLATION='SHOW_INFOWINDOW_VIOLATION'
// export const CLEAR_INFOWINDOW_VIOLATION='CLEAR_INFOWINDOW_VIOLATION'
// export const SearchViolation={
//     GET_SEARCH_VIOLATION_REQUEST:'GET_SEARCH_VIOLATION_REQUEST',
//     GET_SEARCH_VIOLATION_FAILURE:'GET_SEARCH_VIOLATION_FAILURE',
//     GET_SEARCH_VIOLATION_SUCCESS:'GET_SEARCH_VIOLATIO_SUCCESS',
// }
export default {
    GET_SEARCH_VIOLATION_REQUEST:'GET_SEARCH_VIOLATION_REQUEST',
    GET_SEARCH_VIOLATION_FAILURE:'GET_SEARCH_VIOLATION_FAILURE',
    GET_SEARCH_VIOLATION_SUCCESS:'GET_SEARCH_VIOLATIO_SUCCESS',
    SHOW_INFOWINDOW_VIOLATION:'SHOW_INFOWINDOW_VIOLATION',
    CLEAR_INFOWINDOW_VIOLATION:'CLEAR_INFOWINDOW_VIOLATION'
}
 