// export const SHOW_INFOWINDOW_VIOLATION='SHOW_INFOWINDOW_VIOLATION'
// export const CLEAR_INFOWINDOW_VIOLATION='CLEAR_INFOWINDOW_VIOLATION'
// export const SearchViolation={
//     GET_SEARCH_VIOLATION_REQUEST:'GET_SEARCH_VIOLATION_REQUEST',
//     GET_SEARCH_VIOLATION_FAILURE:'GET_SEARCH_VIOLATION_FAILURE',
//     GET_SEARCH_VIOLATION_SUCCESS:'GET_SEARCH_VIOLATIO_SUCCESS',
// }
export default {
    GET_SEARCH_VIOLATION_REQUEST:'GET_SEARCH_VIOLATION_REQUEST',
    GET_SEARCH_VIOLATION_FAILURE:'GET_SEARCH_VIOLATION_FAILURE',
    GET_SEARCH_VIOLATION_SUCCESS:'GET_SEARCH_VIOLATIO_SUCCESS',
    SHOW_INFOWINDOW_VIOLATION:'SHOW_INFOWINDOW_VIOLATION',
    CLEAR_INFOWINDOW_VIOLATION:'CLEAR_INFOWINDOW_VIOLATION',
    DATA_INPUT_SEARCH:'DATA_INPUT_SEARCH',
    CLEAR_DATA_SEARCH:'CLEAR_DATA_SEARCH',
    GET_NOPARKING_VIOLATION_SUCCESS:'GET_NOPARKING_VIOLATION_SUCCESS',
    GET_NOPARKING_VIOLATION_REQUEST:'GET_NOPARKING_VIOLATION_REQUEST',
    GET_NOPARKING_VIOLATION_FAILUTE:'GET_NOPARKING_VIOLATION_FAILUTE'
}
 