export default {
    GET_DATA_NOPARKING_REQUEST: 'GET_DATA_NOPARKING_REQUEST',
    GET_DATA_NOPARKING_SUCCESS: 'GET_DATA_NOPARKING_SUCCESS',
    GET_DATA_NOPARKING_FAILURE: 'GET_DATA_NOPARKING_FAILURE',
}